### ISSUE TITLE
"Content in subtree by class" section does not return correct results

### ISSUE THREAD

**Issue by ivrdoljak** [netgen/ezclasslists#2]
Total count of objects in the "Content in subtree by class" section does not match the sum of the subelements counts. Also, some of the links do not return any objects when clicked

![object counts](https://user-images.githubusercontent.com/586253/59707363-c5f0e700-9202-11e9-887c-ef66ea6e3247.png)

**Comment by pspanja** [comment]
Fixed in https://github.com/netgen/ezclasslists/commit/0b380d4a161c3901db6d0b09df5fe50a05e1500c
